apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-migration-connection
  namespace: webmap-config
spec:
  encryptedData:
    db: AgBsbdMhfMB7rpUy7cS5nyrN9fv+O7cvuXycIk4CrzZow87lUoD1HXZA/NiQEILWupa4DBL23s8yUUfcUc01Rt0P1LCDVOTHYd4TJlUAXUSEpze4TSP2j8xdflVcFawizk8d/ZbQdhYcoTTWxWCl/0HhI9Y7HG/iiUWGN7kGQ0zyMhlVEldmVTSjKusrDPyAYRdksH+FAd3XVEFA7Pb42oipN/4Fr+MHEVLutqKbW1sziWQta+kzjFknl5lxvXpWmPuWX3AhIqJKqtE6MrXG1zl5dS4H/PvXhZj9bOtMyHuTIt6hlt52wFHIBniUicrNpV1NtnooGAYstMOAZQgtK3pdt58fY0bZwA1W3+lhfB5Ss1fjbuEmnM8niwUgZdb5H25nHKP/HsiNPuGysnevPRHz+CRsSyUVI5rU2gH9Y6Ant1ny1deQcuVedXvDlLQFR+Rz1+zmCOq/hfY2xxyKGt5fOOo8EDO94MlV2XPXkAaHYLafij7GDOUesuZI09X9pbHzt2xGHO67Zoi7Kni/aUSShPlideOc0xZkNt39bKLSxvRdAF9f3xlkHcxEyyRwmdyBjxYRKFs2NObTEYE83Yr7+TiuIucVudEDhcUZiZXrUQMDqGz4lNnrFgtvTTlO/1NinsQ7aB9ym9wZyKx8M8lQtewudqowhqU2rHJPNgAmFJVw8yNiHu4fd2O9O3WENuHx7G8G/6IVtC54+BRAnvefqH65W4KXt5yNREHYFToTct9msKWmkTIOlytZ8DmfjkqP+vwSYa1vmYxTdC1I45WJ4/YdaCT7OZqCvtVgnPNL5gsvz+r37fPEbQZtBMlL4Yq81tiTOTf6LD2ZhNdMqa2SI5zIRFVV6l3tcbUSheLyohc8AYXN5Z+6COk/I1SP/lawMA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: database-migration-connection
      namespace: webmap-config

