patchesStrategicMerge:
  - database-migration-connection-sealed-secret.yaml
  - database-connection-sealed-secret.yaml
images:
  - name: greenstand/map-config-api
    newTag: 0.0.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
