apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetracker-map-config-api
  labels:
    app: treetracker-map-config-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: treetracker-map-config-api
  template:
    metadata:
      labels:
        app: treetracker-map-config-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: doks.digitalocean.com/node-pool
                    operator: In
                    values:
                      - microservices-node-pool
      containers:
        - name: treetracker-map-config-api
          image: greenstand/treetracker-map-config-api:TAG
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-connection
                  key: db
            - name: DATABASE_SCHEMA
              value: messaging
